name: Docker page CI/CD

on:
  pull_request:
    branches:
      - 'master'

jobs:
  docker-orchestration:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build da imagem Docker
        run: |
          docker build -t hello-world-page .

      - name: Rodar container
        run: |
          docker run -d --name hello-world -p 8080:80 hello-world-page

      - name: Testa se o container está rodando (localhost)
        run: |
          sleep 5
          curl -I http://localhost:8080 | grep "200 OK"

      - name: Para e remove container
        if: always()
        run: |
          docker stop hello-world
          docker rm hello-world
